### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by sergebezborodov** [tony2001/pinba_engine#50]
Does exist plans for support PHP 7?

**Comment by muxx** [comment]
Look at https://github.com/tony2001/pinba_extension/issues/23

**Comment by yuklia** [comment]
Hello!
I tried to build on FROM php:7.3-fpm and got an error below:
```
/usr/src/php/ext/pinba/pinba.c: In function 'zif_pinba_timer_start':
/usr/src/php/ext/pinba/pinba.c:1295:19: error: lvalue required as increment operand
  GC_REFCOUNT(rsrc)++;
                   ^~
/usr/src/php/ext/pinba/pinba.c: In function 'zif_pinba_timer_add':
/usr/src/php/ext/pinba/pinba.c:1354:19: error: lvalue required as increment operand
  GC_REFCOUNT(rsrc)++;
                   ^~
/usr/src/php/ext/pinba/pinba.c: In function 'zif_pinba_timers_get':
/usr/src/php/ext/pinba/pinba.c:1811:21: error: lvalue required as increment operand
    GC_REFCOUNT(rsrc)++;
                     ^~
make: *** [Makefile:195: pinba.lo] Error 1
```

BUT `FROM php:7.2-fpm` works hist fine 👽

**Comment by gggeek** [comment]
Aside from the fact that this ticket has been created in the wrong issue tracker, you can find a pure-php implementation of Pinba at https://github.com/gggeek/pinba_php/
